# Generated by Django 2.2.5 on 2020-10-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_email_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_confirmed',
            new_name='email_verified',
        ),
    ]
